### PR TITLE
Add note about strict types

### LINKED ISSUE #21: Strict types
Basically the same as https://github.com/async-interop/event-loop/issues/117, callbacks passed to `Promise::when` might contain scalar type declarations.

### PR DESCRIPTION
**Pull request by kelunik**
I think that's enough.

Fixes #21.

### CODE REVIEW

**Review by bwoebi — CHANGES_REQUESTED** [review]
Promise impls may use strict types internally, but only the file invoking the callback must not.

**Comment by kelunik** [comment]
@bwoebi I think it's actually fine as is. I didn't say a package implementing promises. I said that promise implementations... That's the thing that accepts callbacks and calls them. Feel free to suggest another wording.

**Comment by bwoebi** [comment]
Something like:

> Registered callbacks MUST be called in a file without strict types (`declare(strict_types=0);`).

**Comment by kelunik** [comment]
@bwoebi Changed.

**Review by bwoebi — APPROVED** [review]

**Review by trowski — APPROVED** [review]

**Review by WyriHaximus — APPROVED** [review]

**Pull request merged**
