### PR TITLE
Async interop rename

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
**Not ready for merge**

Just making a start on the transition to 'async-interop'

### CODE REVIEW

**Comment by AndrewCarterUK** [comment]
A question here is what namespace do we want to use whilst we're developing these interfaces and testing them?

If we follow the precedent set by container-interop with "Interop\Container", we would use "Interop\Async\Promise" (and likewise "Interop\Async\EventLoop").

Any other suggestions, alternatives or general reasons for/against?

**Comment by jsor** [comment]
:+1: for the suggested namespace.

Regarding the composer package name: they use `container-interop/container-interop`, so according to this logic the package name should be `async-interop/promise-interop`.

Personally, i like `async-interop/promise` better, so :+1: here also.

**Comment by prisis** [comment]
Im to :+1:, for the short namespace async-interop/promise.

**Comment by trowski** [comment]
`Interop\Async\Promise` for the namespace and `async-interop/promise` for the package. :+1:

**Comment by oanhnn** [comment]
Vote :+1: for namespace `Interop\Async\Promise` and package `async-interop/promise`

**Comment by WyriHaximus** [comment]
`Interop\Async\Promise` for the namespace and `async-interop/promise` for the package. :+1:

**Comment by AndrewCarterUK** [comment]
Does that make this ready for merge? Don't think I've missed anything.

**Pull request merged**
